# Generated by Django 5.1.1 on 2025-08-01 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='待办事项的标题，简要描述任务内容', max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='待办事项的详细描述，可选填', null=True, verbose_name='详情')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已取消')], default=0, help_text='待办事项的状态：0-未完成，1-已完成，2-已取消', verbose_name='状态')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], help_text='待办事项的优先级：1-低，2-中，3-高，可选填', null=True, verbose_name='优先级')),
                ('due_time', models.DateTimeField(blank=True, help_text='待办事项的截止时间，可选填', null=True, verbose_name='截止时间')),
                ('category_id', models.BigIntegerField(blank=True, help_text='关联的分类ID，对应t_category表的id字段，可选填', null=True, verbose_name='分类ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='待办事项的创建时间，自动生成，不可修改', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='待办事项最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 't_todo',
                'db_table_comment': '待办事项主表，存储所有待办任务的基本信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag', models.ForeignKey(help_text='关联的标签，对应t_tag表', on_delete=django.db.models.deletion.CASCADE, related_name='todotags', to='tag.tag', verbose_name='标签')),
                ('todo', models.ForeignKey(help_text='关联的待办事项，对应t_todo表', on_delete=django.db.models.deletion.CASCADE, related_name='todotags', to='todo.todo', verbose_name='待办事项')),
            ],
            options={
                'verbose_name': '待办-标签关联',
                'verbose_name_plural': '待办-标签关联',
                'db_table': 't_todo_tag',
                'db_table_comment': '待办事项与标签的关联表，实现多对多关系',
                'ordering': ['-created_at'],
                'unique_together': {('todo', 'tag')},
            },
        ),
    ]
