# Generated by Django 5.1.1 on 2025-07-31 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类的名称，如工作、生活、学习等，不可重复', max_length=100, unique=True, verbose_name='分类名称')),
                ('color', models.CharField(blank=True, help_text='用于前端展示的颜色值，如#FF5733，可选填', max_length=20, null=True, verbose_name='显示颜色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='分类的创建时间，自动生成，不可修改', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='分类信息最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 't_category',
                'db_table_comment': '待办事项的一级分类表，用于对todo进行归类管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签的名称，如紧急、重要、会议等，不可重复', max_length=50, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='标签的创建时间，自动生成', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='标签信息最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
                'db_table_comment': '待办事项的标签表，用于对todo进行更细致的标记，支持多标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='待办事项的标题，简要描述任务内容', max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='待办事项的详细描述，可选填', null=True, verbose_name='详情')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已取消')], default=0, help_text='待办事项的状态：0-未完成，1-已完成，2-已取消', verbose_name='状态')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], help_text='待办事项的优先级：1-低，2-中，3-高，可选填', null=True, verbose_name='优先级')),
                ('due_time', models.DateTimeField(blank=True, help_text='待办事项的截止时间，可选填', null=True, verbose_name='截止时间')),
                ('category_id', models.BigIntegerField(blank=True, help_text='关联的分类ID，对应t_category表的id字段，可选填', null=True, verbose_name='分类ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='待办事项的创建时间，自动生成，不可修改', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='待办事项最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 't_todo',
                'db_table_comment': '待办事项主表，存储所有待办任务的基本信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_id', models.BigIntegerField(help_text='关联的待办事项ID，对应t_todo表的id字段', verbose_name='待办ID')),
                ('tag_id', models.BigIntegerField(help_text='关联的标签ID，对应t_tag表的id字段', verbose_name='标签ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='关联关系的创建时间，自动生成', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='关联关系最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办-标签关联',
                'verbose_name_plural': '待办-标签关联',
                'db_table': 't_todo_tag',
                'db_table_comment': '待办事项与标签的关联表，实现多对多关系',
                'ordering': ['-created_at'],
                'unique_together': {('todo_id', 'tag_id')},
            },
        ),
    ]
