# Generated by Django 5.1.1 on 2025-08-01 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类的名称，如工作、生活、学习等，不可重复', max_length=100, unique=True, verbose_name='分类名称')),
                ('color', models.CharField(blank=True, help_text='用于前端展示的颜色值，如#FF5733，可选填', max_length=20, null=True, verbose_name='显示颜色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='分类的创建时间，自动生成，不可修改', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='分类信息最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 't_category',
                'db_table_comment': '待办事项的一级分类表，用于对todo进行归类管理',
                'ordering': ['name'],
            },
        ),
    ]
