# Generated by Django 5.1.1 on 2025-08-01 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签的名称，如紧急、重要、会议等，不可重复', max_length=50, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='标签的创建时间，自动生成', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='标签信息最后更新的时间，自动更新', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
                'db_table_comment': '待办事项的标签表，用于对todo进行更细致的标记，支持多标签',
                'ordering': ['name'],
            },
        ),
    ]
