# Generated by Django 4.2.7 on 2025-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='用于前端展示的颜色值，如#FF5733，可选填', max_length=20, null=True, verbose_name='显示颜色'),
        ),
    ]
